name: FactionUUIDChat
main: fr.black_eyes.factionsuuidchat.Main
version: 1.6
api-version: 1.13
description: >
             Plugin for Regenerating Chests
softdepend: [Factions, PlaceholderAPI]
depend: [Vault]
commands:
  fchat:
    description: Main Command
    aliases: chat